apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: v3-docs-hasura
  name: v3-docs-hasura
  namespace: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v3-docs-hasura
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: v3-docs-hasura
    spec:
      containers:
        - name: v3-docs-hasura
          image: us-west1-docker.pkg.dev/websitecloud-352908/v3-docs-hasura/v3-docs-hasura:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: '8080'
            - name: OPENREPLAY_INGEST_POINT
              valueFrom:
                secretKeyRef:
                  name: ddn-docs
                  key:  OPENREPLAY_INGEST_POINT
            - name: OPENREPLAY_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: ddn-docs
                  key:  OPENREPLAY_PROJECT_KEY
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: '64Mi'
              cpu: '3m'
            limits:
              memory: '512Mi'
              cpu: '250m'
