apiVersion: v1
kind: Service
metadata:
  labels:
    app: v3-docs-hasura
    hasuraService: custom
  name: v3-docs-hasura
  namespace: hasura
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: v3-docs-hasura
  sessionAffinity: None
  type: ClusterIP